set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
run -b '~/.config/tmux/plugins/tpm/tpm'

set-option -g status-bg '#32302f'
set-option -g status-fg '#ebdbb2'
set-option -g status-right '%H:%M %d-%b-%Y '

set -g default-terminal "tmux-256color"
set -g mouse on
set -g history-limit 10000

unbind C-b
set-option -g prefix C-a
bind C-a send-prefix

bind -n M-s split-window -v -c "#{pane_current_path}" -b
bind -n M-t split-window -h -c "#{pane_current_path}" -b
bind -n M-d kill-pane
bind -n M-x kill-pane -a
bind -n M-f resize-pane -Z
bind -n M-e select-pane -t :.+
bind -n M-i select-pane -t :.-

bind -n M-n previous-window
bind -n M-o next-window
bind d kill-window
bind x kill-window -a

bind k detach

bind s run-shell -b "~/.config/tmux/plugins/tmux-fzf/main.sh"
bind w run-shell -b "~/.config/tmux/plugins/tmux-fzf/scripts/session.sh"
bind f run-shell -b "~/.config/tmux/plugins/tmux-fzf/scripts/window.sh"
bind p run-shell -b "~/.config/tmux/plugins/tmux-fzf/scripts/pane.sh"

bind e run-shell "emacsclient -e '(my-tmux-to-emacs-buffer)'"
bind t copy-mode

bind -T copy-mode w send-keys -X copy-selection-and-cancel
bind -T copy-mode f send-keys -X previous-word
bind -T copy-mode F send-keys -X previous-space
bind -T copy-mode p send-keys -X next-word-end
bind -T copy-mode P send-keys -X next-space-end
bind -T copy-mode a send-keys -X begin-selection
bind -T copy-mode t send-keys -X top-line
bind -T copy-mode v send-keys -X select-line
bind -T copy-mode j send-keys -X start-of-line
bind -T copy-mode l send-keys -X back-to-indentation
bind -T copy-mode u send-keys -X end-of-line
bind -T copy-mode n send-keys -X cursor-left
bind -T copy-mode e send-keys -X cursor-down
bind -T copy-mode i send-keys -X cursor-up
bind -T copy-mode o send-keys -X cursor-right
bind -T copy-mode h send-keys -X select-word
bind -T copy-mode 7 send-keys -X previous-matching-bracket
bind -T copy-mode 8 send-keys -X next-matching-bracket
bind -T copy-mode _ send-keys -X next-paragraph
bind -T copy-mode ( send-keys -X previous-paragraph
bind -T copy-mode = send-keys -X halfpage-up
bind -T copy-mode - send-keys -X halfpage-down
bind -T copy-mode < send-keys -X history-top
bind -T copy-mode > send-keys -X history-bottom
