set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
run -b '~/.config/tmux/plugins/tpm/tpm'

set-option -g status-bg '#32302f'
set-option -g status-fg '#ebdbb2'
set-option -g status-right '%H:%M %d-%b-%Y '

set -g default-terminal "tmux-256color"
set -g mouse on
set -g history-limit 10000
set -g @continuum-restore 'on'

unbind C-b
set-option -g prefix C-a
bind C-a send-prefix

bind -n M-s split-window -v -c "#{pane_current_path}" -b
bind -n M-t split-window -h -c "#{pane_current_path}" -b
bind -n M-x kill-pane
bind -n M-f resize-pane -Z
bind -n M-e select-pane -t :.+
bind -n M-i select-pane -t :.-

bind -n M-n previous-window
bind -n M-o next-window
bind x kill-window

bind s run-shell -b "~/.config/tmux/plugins/tmux-fzf/main.sh"
bind w run-shell -b "~/.config/tmux/plugins/tmux-fzf/scripts/session.sh"
bind f run-shell -b "~/.config/tmux/plugins/tmux-fzf/scripts/window.sh"
bind p run-shell -b "~/.config/tmux/plugins/tmux-fzf/scripts/pane.sh"

bind e run-shell "emacsclient -e '(my-tmux-to-emacs-buffer)'"
bind t copy-mode

bind -T copy-mode-vi n send-keys -X cursor-left
bind -T copy-mode-vi e send-keys -X cursor-down
bind -T copy-mode-vi i send-keys -X cursor-up
bind -T copy-mode-vi o send-keys -X cursor-right
bind -T copy-mode-vi f send-keys -X previous-word
bind -T copy-mode-vi p send-keys -X next-word
bind -T copy-mode-vi l send-keys -X start-of-line
bind -T copy-mode-vi u send-keys -X end-of-line
bind -T copy-mode-vi s send-keys /
bind -T copy-mode-vi r send-keys ?
bind -T copy-mode-vi j send-keys -X search-again
bind -T copy-mode-vi J send-keys -X search-reverse