background {
    monitor =
    color = rgb(28,28,28)
    blur_passes = 0
    blur_size = 7
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

general {
    no_fade_in = true
}

input-field {
    monitor =
    size = 160, 40
    outline_thickness = 3

    dots_size = 0.16
    dots_spacing = 0.15
    dots_center = false
    dots_rounding = -1
    dots_fade_time = 300
    dots_text_format =

    outer_color = rgb(55, 65, 63)
    inner_color = rgb(69, 64, 61)
    font_color = rgb(115, 164, 153)
    check_color = rgb(184, 187, 38)
    fail_color = rgb(204, 36, 29)

    font_family = JetBrains Mono

    fade_on_empty = true
    fade_timeout = 1000

    placeholder_text = <i>零</i>
    hide_input = false

    rounding = -1

    fail_text = <i>Authentication Failed <b>($ATTEMPTS)</b></i>
    fail_timeout = 2000
    fail_transition = 300

    capslock_color = rgb(214, 93, 14)
    numlock_color = rgb(251, 73, 52)
    bothlock_color = rgb(211, 134, 155)

    invert_numlock = false
    swap_font_color = false

    position = 0, -20
    halign = center
    valign = center
}
