(defconst gruvbox-material-colors
  '((bg-dim . "#1b1b1b")
    (bg-dim1 . "#1d2021")
    (bg0 . "#282828")
    (bg1 . "#32302f")
    (bg2 . "#45403d")
    (bg3 . "#5a524c")
    (bg-diff-green . "#34381b")
    (bg-visual-green . "#3b4439")
    (bg-diff-red . "#402120")
    (bg-visual-red . "#4c3432")
    (bg-diff-blue . "#0e363e")
    (bg-visual-blue . "#374141")
    (bg-visual-yellow . "#4f422e")
    (bg-current-word . "#3c3836")
    (fg0 . "#d4be98")
    (fg1 . "#ddc7a1")
    (fg2 . "#e6d0aa")
    (red . "#ea6962")
    (orange . "#e78a4e")
    (yellow . "#d8a657")
    (green . "#a9b665")
    (aqua . "#89b482")
    (blue . "#73a499")
    (purple . "#d3869b")
    (grey0 . "#7c6f64")
    (grey1 . "#928374")
    (grey2 . "#a89984")))

(defun my--gmc (color)
  (assoc-default color gruvbox-material-colors))

(defun my--set-faces ()
  (set-cursor-color (my--gmc 'fg0))
  (custom-set-faces
   '(org-document-title ((t (:inherit outline-1 :height 1.1))))
   '(org-level-1 ((t (:inherit outline-1 :height 1.1))))
   '(org-level-2 ((t (:inherit outline-2 :height 1.0))))
   '(org-level-3 ((t (:inherit outline-3 :height 1.0))))
   '(org-level-4 ((t (:inherit outline-4 :height 1.0))))
   '(org-level-5 ((t (:inherit outline-5 :height 1.0)))))
  (let ((faces `((compilation-info :foreground ,(my--gmc 'bg-visual-blue))
                 (avy-background-face :foreground ,(my--gmc 'grey0))
                 (avy-lead-face :background ,(my--gmc 'bg-dim) :foreground ,(my--gmc 'yellow))
                 (avy-lead-face-0 :background ,(my--gmc 'bg-dim) :foreground ,(my--gmc 'green))
                 (avy-lead-face-1 :background ,(my--gmc 'bg-dim) :foreground ,(my--gmc 'orange))
                 (avy-lead-face-2 :background ,(my--gmc 'bg-dim) :foreground ,(my--gmc 'orange))
                 (line-number :background ,(my--gmc 'bg0) :foreground ,(my--gmc 'grey1))
                 (line-number-current-line :background ,(my--gmc 'bg1) :foreground ,(my--gmc 'fg0))
                 (match :background ,(my--gmc 'bg3) :foreground ,(my--gmc 'fg0))
                 (company-preview :background ,(my--gmc 'blue) :foreground ,(my--gmc 'bg0))
                 (company-preview-search :background ,(my--gmc 'blue) :foreground ,(my--gmc 'bg0))
                 (consult-preview-match :background ,(my--gmc 'blue) :foreground ,(my--gmc 'bg0))
                 (completions-highlight :background ,(my--gmc 'bg2))
                 (minibuffer-depth-indicator :background ,(my--gmc 'bg2))
                 (wgrep-file-face :background ,(my--gmc 'bg2))
                 (vertico-current :background ,(my--gmc 'bg2))
                 (isearch :background ,(my--gmc 'blue) :foreground ,(my--gmc 'bg0))
                 (isearch-fail :background ,(my--gmc 'red) :foreground ,(my--gmc 'bg0))
                 (isearch-group-1 :background ,(my--gmc 'blue) :foreground ,(my--gmc 'bg0))
                 (isearch-group-2 :background ,(my--gmc 'green) :foreground ,(my--gmc 'bg0))
                 (lazy-highlight :background ,(my--gmc 'blue) :foreground ,(my--gmc 'bg0))
                 (vr/group-0 :background ,(my--gmc 'blue) :foreground ,(my--gmc 'bg0))
                 (vr/group-1 :background ,(my--gmc 'green) :foreground ,(my--gmc 'bg0))
                 (vr/group-2 :background ,(my--gmc 'yellow) :foreground ,(my--gmc 'bg0))
                 (vr/match-0 :background ,(my--gmc 'blue) :foreground ,(my--gmc 'bg0))
                 (vr/match-1 :background ,(my--gmc 'blue) :foreground ,(my--gmc 'bg0))
                 (orderless-match-face-0 :foreground ,(my--gmc 'yellow))
                 (orderless-match-face-1 :foreground ,(my--gmc 'yellow))
                 (orderless-match-face-2 :foreground ,(my--gmc 'yellow))
                 (orderless-match-face-3 :foreground ,(my--gmc 'yellow))
                 (diredfl-symlink :foreground ,(my--gmc 'grey2))
                 (persp-selected-face :foreground ,(my--gmc 'yellow))
                 (magit-header-line :foreground ,(my--gmc 'yellow))
                 (magit-section-heading :foreground ,(my--gmc 'yellow))
                 (magit-diff-added-highlight :foreground ,(my--gmc 'green))
                 (magit-diff-removed-highlight :foreground ,(my--gmc 'red))
                 (magit-branch-local :foreground ,(my--gmc 'blue))
                 (font-lock-bracket-face :foreground ,(my--gmc 'grey3))
                 (font-lock-builtin-face :foreground ,(my--gmc 'orange))
                 (font-lock-comment-face :foreground ,(my--gmc 'grey2))
                 (font-lock-comment-delimiter-face :foreground ,(my--gmc 'grey2))
                 (font-lock-constant-face :foreground ,(my--gmc 'orange))
                 (font-lock-delimiter-face :foreground ,(my--gmc 'fg1))
                 (font-lock-doc-face :foreground ,(my--gmc 'green))
                 (font-lock-doc-markup-face :foreground ,(my--gmc 'green))
                 (font-lock-escape-face :foreground ,(my--gmc 'red))
                 (font-lock-function-name-face :foreground ,(my--gmc 'orange))
                 (font-lock-function-call-face :foreground ,(my--gmc 'orange))
                 (font-lock-keyword-face :foreground ,(my--gmc 'red))
                 (font-lock-misc-punctuation-face :foreground ,(my--gmc 'fg1))
                 (font-lock-negation-char-face :foreground ,(my--gmc 'red))
                 (font-lock-number-face :foreground ,(my--gmc 'green))
                 (font-lock-operator-face :foreground ,(my--gmc 'fg1))
                 (font-lock-preprocessor-face :foreground ,(my--gmc 'yellow))
                 (font-lock-property-name-face :foreground ,(my--gmc 'fg1))
                 (font-lock-property-use-face :foreground ,(my--gmc 'fg1))
                 (font-lock-punctuation-face :foreground ,(my--gmc 'fg1))
                 (font-lock-regexp-face :foreground ,(my--gmc 'orange))
                 (font-lock-regexp-grouping-backslash :foreground ,(my--gmc 'orange))
                 (font-lock-regexp-grouping-construct :foreground ,(my--gmc 'orange))
                 (font-lock-string-face :foreground ,(my--gmc 'green))
                 (font-lock-type-face :foreground ,(my--gmc 'yellow))
                 (font-lock-variable-name-face :foreground ,(my--gmc 'fg0))
                 (font-lock-variable-use-face :foreground ,(my--gmc 'fg0))
                 (font-lock-warning-face :foreground ,(my--gmc 'red))
                 (vundo-highlight :foreground ,(my--gmc 'green))
                 (vundo-saved :foreground ,(my--gmc 'aqua))
                 (vundo-last-saved :foreground ,(my--gmc 'aqua))
                 (compilation-info :foreground ,(my--gmc 'green))
                 (compilation-mode-line-exit :foreground ,(my--gmc 'green))
                 (compilation-mode-line-fail :foreground ,(my--gmc 'red))
                 (compilation-info :foreground ,(my--gmc 'green))
                 (mode-line-active :background ,(my--gmc 'bg1)  :box (:line-width 1 :color "#445450" :style nil))
                 (mode-line-inactive :background ,(my--gmc 'bg0) :box (:line-width 1 :color ,(my--gmc 'bg1) :style nil))
                 (mode-line-buffer-id :foreground ,(my--gmc 'green)))))
    (dolist (face faces)
      (apply #'set-face-attribute (car face) nil (cdr face)))))

(load-theme 'gruvbox-dark-medium :no-confirm)
(my--set-faces)
