;;; -*- lexical-binding: t; coding: utf-8 -*-

(deftheme gruvbox-material-medium
  "gruvbox material medium")

(defconst gruvbox-material-colors
  '((bg-dim . "#181818")
    (bg-dim1 . "#1b1b1b")
    (bg-dim2 . "#1d2021")
    (bg0 . "#282828")
    (bg1 . "#32302f")
    (bg2 . "#45403d")
    (bg3 . "#5a524c")
    (bg-diff-green . "#34381b")
    (bg-visual-green . "#424937")
    (bg-diff-red . "#402120")
    (bg-visual-red . "#4a2b29")
    (bg-diff-blue . "#0e363e")
    (bg-visual-blue . "#374141")
    (bg-visual-yellow . "#4f422e")
    (bg-visual-yellow2 . "#8a734f")
    (bg-current-word . "#3c3836")
    (fg0 . "#d4be98")
    (fg1 . "#ddc7a1")
    (fg2 . "#e6d0aa")
    (red . "#ea6962")
    (orange . "#e38a53")
    (yellow . "#d8a657")
    (green . "#a9b665")
    (aqua . "#89b482")
    (dark-aqua . "#445450")
    (grey-blue . "#95a99f")
    (blue . "#7daea3")
    (purple . "#d3869b")
    (grey0 . "#7c6f64")
    (grey1 . "#928374")
    (grey2 . "#a89984")))

(defun gmc (color-name)
  (cdr (assoc color-name gruvbox-material-colors)))

(let ((bg-dim (gmc 'bg-dim))
      (bg-dim1 (gmc 'bg-dim1))
      (bg-dim2 (gmc 'bg-dim2))
      (bg0 (gmc 'bg0))
      (bg1 (gmc 'bg1))
      (bg2 (gmc 'bg2))
      (bg3 (gmc 'bg3))
      (bg-diff-green (gmc 'bg-diff-green))
      (bg-visual-green (gmc 'bg-visual-green))
      (bg-diff-red (gmc 'bg-diff-red))
      (bg-visual-red (gmc 'bg-visual-red))
      (bg-diff-blue (gmc 'bg-diff-blue))
      (bg-visual-blue (gmc 'bg-visual-blue))
      (bg-visual-yellow (gmc 'bg-visual-yellow))
      (bg-visual-yellow2 (gmc 'bg-visual-yellow2))
      (bg-current-word (gmc 'bg-current-word))
      (fg0 (gmc 'fg0))
      (fg1 (gmc 'fg1))
      (fg2 (gmc 'fg2))
      (red (gmc 'red))
      (orange (gmc 'orange))
      (yellow (gmc 'yellow))
      (green (gmc 'green))
      (aqua (gmc 'aqua))
      (dark-aqua (gmc 'dark-aqua))
      (blue (gmc 'blue))
      (grey-blue (gmc 'grey-blue))
      (purple (gmc 'purple))
      (grey0 (gmc 'grey0))
      (grey1 (gmc 'grey1))
      (grey2 (gmc 'grey2)))

  (custom-theme-set-faces
   'gruvbox-material-medium

   `(default ((t (:foreground ,fg0 :background ,bg0))))
   `(cursor ((t (:foreground ,bg0 :background ,fg0))))
   `(region ((t (:background ,bg2))))
   `(hl-line ((t (:background ,bg1))))
   `(error ((t (:foreground ,red))))
   `(warning ((t (:foreground ,yellow))))
   `(success ((t (:foreground ,green))))
   `(secondary-selection ((t (:background ,bg1))))
   `(highlight ((t (:background ,bg2))))
   `(fringe ((t (:foreground ,grey1 :background ,bg0))))
   `(header-line ((t (:foreground ,fg1 :background ,bg1))))
   `(minibuffer-prompt ((t (:foreground ,green :weight bold))))
   `(vertical-border ((t (:foreground ,bg2))))
   `(internal-border ((t (:foreground ,bg2))))
   `(window-divider ((t (:foreground ,bg2))))
   `(link ((t (:foreground ,grey2))))
   `(shadow ((t (:foreground ,grey2))))
   `(bold ((t (:weight bold))))
   `(bold-italic ((t (:weight bold :slant italic))))
   `(italic ((t (:slant italic))))
   `(underline ((t (:underline t))))
   `(help-key-binding ((t (:foreground ,grey-blue))))
   `(bookmark-face ((t (:foreground ,grey-blue))))
   `(escape-glyph ((t (:foreground ,grey-blue))))
   `(homoglyph ((t (:foreground ,grey-blue))))

   `(font-lock-bracket-face ((t (:foreground ,grey2))))
   `(font-lock-builtin-face ((t (:foreground ,orange))))
   `(font-lock-comment-face ((t (:foreground ,bg-visual-yellow2))))
   `(font-lock-comment-delimiter-face ((t (:foreground ,bg-visual-yellow2))))
   `(font-lock-constant-face ((t (:foreground ,orange))))
   `(font-lock-delimiter-face ((t (:foreground ,fg1))))
   `(font-lock-doc-face ((t (:foreground ,green))))
   `(font-lock-doc-markup-face ((t (:foreground ,green))))
   `(font-lock-escape-face ((t (:foreground ,red))))
   `(font-lock-function-name-face ((t (:foreground ,orange))))
   `(font-lock-function-call-face ((t (:foreground ,orange))))
   `(font-lock-keyword-face ((t (:foreground ,red))))
   `(font-lock-misc-punctuation-face ((t (:foreground ,fg1))))
   `(font-lock-negation-char-face ((t (:foreground ,red))))
   `(font-lock-number-face ((t (:foreground ,green))))
   `(font-lock-operator-face ((t (:foreground ,fg1))))
   `(font-lock-preprocessor-face ((t (:foreground ,yellow))))
   `(font-lock-property-name-face ((t (:foreground ,fg1))))
   `(font-lock-property-use-face ((t (:foreground ,fg1))))
   `(font-lock-punctuation-face ((t (:foreground ,fg1))))
   `(font-lock-regexp-face ((t (:foreground ,orange))))
   `(font-lock-regexp-grouping-backslash ((t (:foreground ,orange))))
   `(font-lock-regexp-grouping-construct ((t (:foreground ,orange))))
   `(font-lock-string-face ((t (:foreground ,green))))
   `(font-lock-type-face ((t (:foreground ,yellow))))
   `(font-lock-variable-name-face ((t (:foreground ,fg0))))
   `(font-lock-variable-use-face ((t (:foreground ,fg0))))
   `(font-lock-warning-face ((t (:foreground ,red))))

   `(line-number ((t (:foreground ,grey1 :background ,bg0))))
   `(line-number-current-line ((t (:foreground ,fg0 :background ,bg1))))

   `(show-paren-match ((t(:foreground ,blue :background ,bg2 :weight bold))))
   `(show-paren-match-expression ((t(:foreground ,red :background ,bg2 :weight bold))))
   `(show-paren-mismatch ((t(:foreground ,red :background ,bg2 :weight bold))))

   `(mode-line ((t (:foreground ,fg0 :background ,bg1 :box (:line-width 1 :color ,dark-aqua :style nil)))))
   `(mode-line-active ((t (:foreground ,fg0 :background ,bg1 :box (:line-width 1 :color ,dark-aqua :style nil)))))
   `(mode-line-inactive ((t (:foreground ,grey1 :background ,bg0 :box (:line-width 1 :color ,bg1 :style nil)))))
   `(mode-line-buffer-id ((t (:foreground ,green :background ,bg1))))

   `(match ((t (:background ,bg2))))
   `(lazy-highlight ((t (:background ,bg2))))

   `(isearch ((t (:foreground ,fg2 :background ,bg3))))
   `(isearch-fail ((t (:foreground ,bg0 :background ,red))))
   `(isearch-group-1 ((t (:background ,bg0))))
   `(isearch-group-2 ((t (:background ,bg0))))

   `(corfu-default ((t (:foreground ,fg0 :background ,bg1))))
   `(corfu-current ((t (:foreground ,fg2 :background ,bg2))))
   `(corfu-bar ((t (:background ,bg2))))
   `(corfu-border ((t (:background ,bg1))))
   `(corfu-annotations ((t (:foreground ,fg2 :background ,bg1))))
   `(corfu-deprecated ((t (:foreground ,fg2 :strike-through t))))

   `(ido-first-match ((t (:foreground ,green))))
   `(ido-only-match ((t (:foreground ,green))))
   `(ido-subdir ((t (:inherit dired-directory))))
   `(ido-virtual ((t (:foreground ,blue))))
   `(ido-incomplete-regexp ((t (:inherit warning))))
   `(ido-indicator ((t (:foreground ,fg0 :weight bold))))

   `(completions-highlight ((t (:background ,bg2))))
   `(completions-common-part ((t (:foreground ,yellow))))
   `(completions-annotations ((t (:foreground ,grey1 :background ,bg0))))
   `(completions-group-title ((t (:foreground ,grey1 :background ,bg0))))
   `(completions-group-separator ((t (:foreground ,grey1 :background ,bg0))))

   `(consult-preview-match ((t (:foreground ,fg2 :background ,bg3))))
   `(consult-file ((t (:foreground ,orange))))
   `(consult-highlight-mark ((t (:foreground ,fg2 :background ,bg3))))
   `(consult-highlight-match ((t (:foreground ,fg2 :background ,bg2))))
   `(consult-preview-insertion ((t (:foreground ,fg2 :background ,bg3))))
   `(consult-preview-line ((t (:foreground ,fg2 :background ,bg3))))
   `(consult-key ((t (:foreground ,fg0 :background ,bg3))))
   `(consult-help ((t (:foreground ,fg0 :background ,bg3))))
   `(consult-grep-context ((t (:foreground ,grey1 :background ,bg3))))
   `(consult-line-number ((t (:foreground ,grey1 :background ,bg0))))
   `(consult-line-number-prefix ((t (:foreground ,grey1 :background ,bg0))))
   `(consult-line-number-wrapped ((t (:foreground ,grey1 :background ,bg0))))

   `(vertico-current ((t (:background ,bg2))))
   `(vertico-group-title ((t (:foreground ,grey2 :inherit bold))))
   `(vertico-group-separator ((t (:foreground ,green :strike-through ,grey1))))

   `(vertico-posframe ((t (:foreground ,fg0 :background ,bg1))))
   `(vertico-posframe-border ((t (:background ,grey2))))

   `(orderless-match-face-0 ((t (:foreground ,fg2 :background ,bg2))))
   `(orderless-match-face-1 ((t (:foreground ,fg2 :background ,bg2))))
   `(orderless-match-face-2 ((t (:foreground ,fg2 :background ,bg2))))
   `(orderless-match-face-3 ((t (:foreground ,fg2 :background ,bg2))))

   `(compilation-info ((t (:foreground ,green))))
   `(compilation-line-number ((t (:foreground ,green))))
   `(compilation-column-number ((t (:foreground ,green))))
   `(compilation-mode-line-exit ((t (:foreground ,green))))
   `(compilation-warning ((t (:foreground ,yellow))))
   `(compilation-mode-line-run ((t (:foreground ,yellow))))
   `(compilation-error ((t (:foreground ,red))))
   `(compilation-mode-line-fail ((t (:foreground ,red))))

   `(mc/cursor-face ((t (:foreground ,bg0 :background ,fg0))))
   `(mc/region-face ((t (:inherit region))))

   `(vr/group-0 ((t (:foreground ,bg0 :background ,grey-blue))))
   `(vr/group-1 ((t (:foreground ,bg0 :background ,green))))
   `(vr/group-2 ((t (:foreground ,bg0 :background ,yellow))))
   `(vr/match-0 ((t (:foreground ,bg0 :background ,grey-blue))))
   `(vr/match-1 ((t (:foreground ,bg0 :background ,green))))
   `(vr/match-separator-face ((t (:foreground ,bg0 :background ,red))))

   `(avy-background-face ((t (:foreground ,grey0))))
   `(avy-lead-face ((t (:foreground ,yellow :background ,bg-dim))))
   `(avy-lead-face-0 ((t (:foreground ,green :background ,bg-dim))))
   `(avy-lead-face-1 ((t (:foreground ,orange :background ,bg-dim))))
   `(avy-lead-face-2 ((t (:foreground ,orange :background ,bg-dim))))

   `(dired-broken-symlink ((t (:foreground ,fg0 :background ,bg-diff-red))))

   `(diredfl-symlink ((t (:foreground ,grey2))))
   `(diredfl-dir-name ((t (:foreground ,blue))))
   `(diredfl-dir-heading ((t (:foreground ,blue))))
   `(diredfl-file-name ((t (:foreground ,fg0))))
   `(diredfl-file-suffix ((t (:foreground ,fg0))))
   `(diredfl-deletion ((t (:foreground ,red))))
   `(diredfl-deletion-file-name ((t (:foreground ,red))))
   `(diredfl-number ((t (:foreground ,fg0))))
   `(diredfl-date-time ((t (:foreground ,aqua))))
   `(diredfl-flag-mark ((t (:foreground ,yellow :background ,bg1))))
   `(diredfl-flag-mark-line ((t (:foreground ,yellow :background ,bg1))))
   `(diredfl-dir-priv ((t (:foreground ,blue))))
   `(diredfl-read-priv ((t (:foreground ,green))))
   `(diredfl-write-priv ((t (:foreground ,yellow))))
   `(diredfl-exec-priv ((t (:foreground ,red))))
   `(diredfl-link-priv ((t (:foreground ,grey2))))
   `(diredfl-no-priv ((t (:foreground ,fg0))))
   `(diredfl-autofile-name ((t (:foreground ,grey1))))
   `(diredfl-compressed-file-name ((t (:foreground ,grey2))))
   `(diredfl-compressed-file-suffix ((t (:foreground ,grey2))))
   `(diredfl-ignored-file-name ((t (:foreground ,grey2))))
   `(diredfl-executable-tag ((t (:foreground ,red))))
   `(diredfl-other-priv ((t (:foreground ,fg0))))
   `(diredfl-rare-priv ((t (:foreground ,fg0))))
   `(diredfl-tagged-autofile-name ((t (:foreground ,grey1))))

   `(org-document-title ((t (:inherit outline-1 :height 1.1))))
   `(org-level-1 ((t (:foreground ,orange :height 1.1))))
   `(org-level-2 ((t (:foreground ,yellow :height 1.0))))
   `(org-level-3 ((t (:foreground ,blue :height 1.0))))
   `(org-level-4 ((t (:foreground ,green :height 1.0))))
   `(org-level-5 ((t (:foreground ,aqua :height 1.0))))
   `(org-level-6 ((t (:foreground ,grey-blue :height 1.0))))
   `(org-level-7 ((t (:foreground ,purple :height 1.0))))
   `(org-level-8 ((t (:foreground ,orange :height 1.0))))
   `(org-link ((t (:foreground ,grey2 :underline ,grey2))))
   `(org-todo ((t (:foreground ,red))))
   `(org-done ((t (:foreground ,aqua :weight bold))))
   `(org-warning ((t (:foreground ,red))))
   `(org-hide ((t (:foreground ,bg0))))
   `(org-special-keyword ((t (:inherit font-lock-comment-face))))
   `(org-drawer ((t (:inherit font-lock-function-name-face))))
   `(org-column ((t (:background ,bg0))))
   `(org-column-title ((t (:background ,bg0 :underline t :weight bold))))
   `(org-archived ((t (:foreground ,fg0 :weight bold))))
   `(org-footnote ((t (:foreground ,aqua :underline t))))
   `(org-ellipsis ((t (:foreground ,grey2))))
   `(org-date ((t (:foreground ,blue :underline t))))
   `(org-sexp-date ((t (:foreground ,blue :underline t))))
   `(org-tag ((t (:weight bold))))
   `(org-list-dt ((t (:weight bold))))
   `(org-agenda-done ((t (:foreground ,aqua))))
   `(org-headline-done ((t (:foreground ,aqua))))
   `(org-table ((t (:foreground ,blue))))
   `(org-block ((t (:background ,bg1))))
   `(org-block-begin-line ((t (:background ,bg1))))
   `(org-block-end-line ((t (:background ,bg1))))
   `(org-formula ((t (:foreground ,yellow))))
   `(org-document-info ((t (:foreground ,blue))))
   `(org-agenda-structure ((t (:inherit font-lock-comment-face))))
   `(org-agenda-date-today ((t (:foreground ,fg0 :weight bold :slant italic))))
   `(org-scheduled ((t (:foreground ,yellow))))
   `(org-scheduled-today ((t (:foreground ,blue))))
   `(org-scheduled-previously ((t (:foreground ,red))))
   `(org-upcoming-deadline ((t (:inherit font-lock-keyword-face))))
   `(org-deadline-announce ((t (:foreground ,red))))
   `(org-time-grid ((t (:foreground ,orange))))
   `(org-latex-and-related ((t (:foreground ,blue))))

   `(markdown-header-face-1 ((t (:foreground ,orange))))
   `(markdown-header-face-2 ((t (:foreground ,yellow))))
   `(markdown-header-face-3 ((t (:foreground ,green))))
   `(markdown-header-face-4 ((t (:foreground ,blue))))
   `(markdown-header-face-5 ((t (:foreground ,orange))))
   `(markdown-header-face-6 ((t (:foreground ,yellow))))

   `(magit-header-line ((t (:foreground ,yellow))))
   `(magit-section-heading ((t (:foreground ,yellow))))
   `(magit-branch-remote ((t (:foreground ,green))))
   `(magit-branch-local ((t (:foreground ,blue))))
   `(magit-branch-current ((t (:underline ,blue :inherit magit-branch-local))))
   `(magit-diff-added ((t (:foreground ,green))))
   `(magit-diff-added-highlight ((t (:foreground ,green :background ,bg1))))
   `(magit-diff-removed ((t (:foreground ,red))))
   `(magit-diff-removed-highlight ((t (:foreground ,red :background ,bg1))))
   `(magit-diff-base ((t (:foreground ,yellow :background ,bg0))))
   `(magit-diff-base-highlight ((t (:foreground ,yellow :background ,bg0))))
   `(magit-diff-context ((t (:foreground ,fg1))))
   `(magit-diff-context-highlight ((t (:foreground ,fg0 :background ,bg0))))
   `(magit-diff-hunk-heading ((t (:foreground ,fg0 :background ,bg1))))
   `(magit-diff-hunk-heading-highlight ((t (:foreground ,fg0 :background ,bg2))))
   `(magit-diff-hunk-heading-selection ((t (:foreground ,fg0 :background ,bg1))))
   `(magit-diff-lines-boundary ((t (:foreground ,orange :background ,bg0))))
   `(magit-diff-lines-heading ((t (:foreground ,orange :background ,bg0))))
   `(magit-diff-whitespace-warning ((t (:foreground ,red :background ,bg0))))
   `(magit-diffstat-added ((t (:foreground ,green))))
   `(magit-diffstat-removed ((t (:foreground ,red))))
   `(magit-process-ok ((t (:foreground ,green))))
   `(magit-process-ng ((t (:foreground ,red))))
   `(magit-log-author ((t (:foreground ,red))))
   `(magit-log-date ((t (:foreground ,aqua))))
   `(magit-log-graph ((t (:foreground ,grey0))))
   `(magit-log-message ((t (:foreground ,fg0))))
   `(magit-reflog-cherry-pick ((t (:foreground ,green))))
   `(magit-reflog-commit ((t (:foreground ,green))))
   `(magit-reflog-merge ((t (:foreground ,green))))
   `(magit-reflog-reset ((t (:foreground ,red))))
   `(magit-reflog-amend ((t (:foreground ,purple))))
   `(magit-reflog-checkout ((t (:foreground ,grey-blue))))
   `(magit-reflog-other ((t (:foreground ,aqua))))
   `(magit-reflog-rebase ((t (:foreground ,purple))))
   `(magit-reflog-remote ((t (:foreground ,grey-blue))))
   `(magit-sequence-stop ((t (:foreground ,green))))
   `(magit-sequence-drop ((t (:foreground ,yellow))))
   `(magit-sequence-head ((t (:foreground ,aqua))))
   `(magit-sequence-part ((t (:foreground ,yellow))))
   `(magit-signature-good ((t (:foreground ,green))))
   `(magit-signature-bad ((t (:foreground ,red))))
   `(magit-signature-error ((t (:foreground ,red))))
   `(magit-signature-expired ((t (:foreground ,orange))))
   `(magit-signature-revoked ((t (:foreground ,purple))))
   `(magit-signature-untrusted ((t (:foreground ,grey-blue))))
   `(magit-bisect-bad ((t (:foreground ,red))))
   `(magit-bisect-good ((t (:foreground ,green))))
   `(magit-bisect-skip ((t (:foreground ,yellow))))
   `(magit-mode-line-process-error ((t (:foreground ,red))))
   `(magit-blame-heading ((t (:foreground ,grey2 :background ,bg1))))
   `(magit-cherry-equivalent ((t (:foreground ,purple))))
   `(magit-cherry-unmatched ((t (:foreground ,aqua))))
   `(magit-dimmed ((t (:foreground ,grey0))))
   `(magit-hash ((t (:foreground ,grey-blue))))
   `(magit-refname ((t (:foreground ,grey2))))
   `(magit-section-heading-selection ((t (:foreground ,yellow))))
   `(magit-section-highlight ((t (:background ,bg1))))
   `(magit-tag ((t (:foreground ,yellow))))

   `(git-commit-summary ((t (:foreground ,fg0))))
   `(git-commit-overlong-summary ((t (:foreground ,yellow))))
   `(git-commit-nonempty-second-line ((t (:foreground ,red))))

   `(diff-header ((t (:foreground ,fg0 :background ,bg2))))
   `(diff-file-header ((t (:foreground ,fg0 :background ,bg2))))
   `(diff-hunk-header ((t (:foreground ,fg0 :background ,bg2))))
   `(diff-context ((t (:foreground ,fg0 :background ,bg0))))
   `(diff-added ((t (:foreground ,green :background ,bg0))))
   `(diff-removed ((t (:foreground ,red :background ,bg0))))
   `(diff-refine-added ((t (:foreground ,fg2 :background ,bg-visual-green))))
   `(diff-refine-changed ((t (:foreground ,fg2 :background ,bg-visual-red))))
   `(diff-refine-removed ((t (:foreground ,fg2 :background ,bg-visual-red))))
   `(diff-indicator-added ((t (:foreground ,green))))
   `(diff-indicator-removed ((t (:foreground ,red))))

   `(ediff-current-diff-A ((t (:background ,bg-visual-red))))
   `(ediff-current-diff-Ancestor ((t (:background ,bg-visual-blue))))
   `(ediff-current-diff-B ((t (:background ,bg-visual-green))))
   `(ediff-current-diff-C ((t (:background ,bg-visual-yellow))))
   `(ediff-even-diff-A ((t (:background ,bg-visual-red))))
   `(ediff-even-diff-Ancestor ((t (:background ,bg-visual-blue))))
   `(ediff-even-diff-B ((t (:background ,bg-visual-green))))
   `(ediff-even-diff-C ((t (:background ,bg-visual-yellow))))
   `(ediff-fine-diff-A ((t (:background ,bg-visual-red))))
   `(ediff-fine-diff-Ancestor ((t (:background ,bg-visual-blue))))
   `(ediff-fine-diff-B ((t (:background ,bg-visual-green))))
   `(ediff-fine-diff-C ((t (:background ,bg-visual-yellow))))
   `(ediff-odd-diff-A ((t (:background ,bg-visual-red))))
   `(ediff-odd-diff-Ancestor ((t (:background ,bg-visual-blue))))
   `(ediff-odd-diff-B ((t (:background ,bg-visual-green))))
   `(ediff-odd-diff-C ((t (:background ,bg-visual-yellow))))

   `(smerge-base ((t (:background ,bg-visual-blue))))
   `(smerge-lower ((t (:background ,bg-visual-green))))
   `(smerge-upper ((t (:background ,bg-visual-red))))
   `(smerge-refined-removed ((t (:foreground ,fg2 :background ,bg-visual-red))))
   `(smerge-refined-changed ((t (:foreground ,fg2 :background ,bg-visual-red))))
   `(smerge-refined-added ((t (:foreground ,fg2 :background ,bg-visual-green))))

   `(whitespace-hspace ((t (:foreground ,bg1 :background ,bg0))))
   `(whitespace-indentation ((t (:foreground ,bg1 :background ,bg0))))
   `(whitespace-newline ((t (:foreground ,bg1 :background ,bg0))))
   `(whitespace-space ((t (:foreground ,bg1 :background ,bg0))))
   `(whitespace-space-after-tab ((t (:foreground ,bg1 :background ,bg0))))
   `(whitespace-space-before-tab ((t (:foreground ,bg1 :background ,bg0))))
   `(whitespace-missing-newline-at-eof ((t (:foreground ,bg1 :background ,bg0))))
   `(whitespace-tab ((t (:foreground ,bg3 :background ,bg0))))
   `(whitespace-trailing ((t (:foreground ,red :background ,bg0))))
   `(whitespace-line ((t (:foreground ,red :background ,bg0))))
   `(whitespace-empty ((t (:foreground unspecified :background unspecified))))

   `(flycheck-error ((t (:underline (:style wave :color ,red)))))
   `(flycheck-warning ((t (:underline (:style wave :color ,yellow)))))
   `(flycheck-info ((t (:underline (:style wave :color ,blue)))))
   `(flycheck-fringe-warning ((t (:foreground ,yellow))))
   `(flycheck-fringe-error ((t (:foreground ,red))))
   `(flycheck-fringe-info ((t (:foreground ,blue))))
   `(flycheck-error-list-warning ((t (:foreground ,yellow :weight bold))))
   `(flycheck-error-list-error ((t (:foreground ,red :weight bold))))
   `(flycheck-error-list-info ((t (:foreground ,blue :weight bold))))

   `(flymake-error ((t (:underline (:style wave :color ,red)))))
   `(flymake-warning ((t (:underline (:style wave :color ,yellow)))))
   `(flymake-note ((t (:underline (:style wave :color ,blue)))))

   `(wgrep-file-face ((t (:background ,bg2))))
   `(wgrep-reject-face ((t (:foreground ,red))))
   `(wgrep-delete-face ((t (:strike-through ,red))))
   `(wgrep-done-face ((t (:foreground ,blue))))
   `(wgrep-face ((t (:foreground ,fg0))))

   `(vundo-highlight ((t (:foreground ,green))))
   `(vundo-saved ((t (:foreground ,aqua))))
   `(vundo-last-saved ((t (:foreground ,aqua))))

   `(minibuffer-depth-indicator ((t (:background ,bg2))))
   `(persp-selected-face ((t (:foreground ,green))))
   `(eglot-mode-line ((t (:foreground ,green :weight medium))))
   `(marginalia-documentation ((t (:foreground ,fg0 :italic t))))

   `(eshell-prompt ((t (:foreground ,aqua))))
   `(eshell-ls-archive ((t (:foreground ,fg1))))
   `(eshell-ls-backup ((t (:foreground ,grey2))))
   `(eshell-ls-clutter ((t (:foreground ,orange))))
   `(eshell-ls-directory ((t (:foreground ,yellow))))
   `(eshell-ls-executable ((t (:weight bold))))
   `(eshell-ls-missing ((t (:foreground ,red))))
   `(eshell-ls-product ((t (:foreground ,red))))
   `(eshell-ls-readonly ((t (:foreground ,fg2))))
   `(eshell-ls-special ((t (:foreground ,yellow))))
   `(eshell-ls-symlink ((t (:foreground ,red))))
   `(eshell-ls-unreadable ((t (:foreground ,red))))

   `(ansi-color-black ((t (:foreground ,bg-dim2 :background ,bg1))))
   `(ansi-color-red ((t (:foreground ,red :background ,red))))
   `(ansi-color-green ((t (:foreground ,green :background ,green))))
   `(ansi-color-yellow ((t (:foreground ,yellow :background ,yellow))))
   `(ansi-color-blue ((t (:foreground ,blue :background ,blue))))
   `(ansi-color-magenta ((t (:foreground ,purple :background ,purple))))
   `(ansi-color-cyan ((t (:foreground ,aqua :background ,aqua))))
   `(ansi-color-white ((t (:foreground ,fg1 :background ,fg1))))
   `(ansi-color-bright-black ((t (:foreground ,bg-dim2 :background ,bg1))))
   `(ansi-color-bright-red ((t (:foreground ,red :background ,red))))
   `(ansi-color-bright-green ((t (:foreground ,green :background ,green))))
   `(ansi-color-bright-yellow ((t (:foreground ,yellow :background ,yellow))))
   `(ansi-color-bright-blue ((t (:foreground ,blue :background ,blue))))
   `(ansi-color-bright-magenta ((t (:foreground ,purple :background ,purple))))
   `(ansi-color-bright-cyan ((t (:foreground ,aqua :background ,aqua))))
   `(ansi-color-bright-white ((t (:foreground ,fg1 :background ,fg1))))

   `(transient-heading ((t (:foreground ,fg0))))
   `(transient-key ((t (:foreground ,green))))
   `(transient-key-stack ((t (:foreground ,green))))
   `(transient-key-stay ((t (:foreground ,grey-blue))))
   `(transient-key-recurse ((t (:foreground ,grey-blue))))
   `(transient-key-exit ((t (:foreground ,blue))))
   `(transient-argument ((t (:foreground ,green))))
   `(transient-value ((t (:foreground ,green))))
   `(transient-inactive-argument ((t (:foreground ,grey1))))
   `(transient-inactive-value ((t (:foreground ,grey0))))
   `(transient-unreachable ((t (:foreground ,grey0))))
   `(transient-unreachable-key ((t (:foreground ,grey0))))
   `(transient-nonstandard-key ((t (:foreground ,orange))))
   `(transient-mismatched-key ((t (:foreground ,red))))
   `(transient-enabled-suffix ((t (:foreground ,green))))
   `(transient-disabled-suffix ((t (:foreground ,grey1))))
   `(transient-separator ((t (:foreground ,grey1))))
   `(transient-pink ((t (:foreground ,grey-blue))))
   `(transient-blue ((t (:foreground ,blue))))
   `(transient-red ((t (:foreground ,red))))
   `(transient-green ((t (:foreground ,green))))
   `(transient-yellow ((t (:foreground ,yellow))))
   `(transient-orange ((t (:foreground ,orange))))
   `(transient-aqua ((t (:foreground ,aqua))))
   ))

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'gruvbox-material-medium)

;;; gruvbox-material-medium-theme.el ends here
