(setq custom-file (locate-user-emacs-file "custom.el"))
(load custom-file :no-error-if-file-is-missing)
(setq create-lockfiles nil)
(setq disabled-command-function nil)

(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(require 'use-package)
(setq use-package-always-ensure t)
(package-initialize)
(unless package-archive-contents
  (package-refresh-contents))

(use-package ibuffer)
(use-package meow)
(use-package vertico)
(use-package orderless)
(use-package marginalia)
(use-package consult)
(use-package consult-eglot)
(use-package embark)
(use-package embark-consult)
(use-package company)
(use-package expand-region)
(use-package multiple-cursors)
(use-package visual-regexp)
(use-package visual-regexp-steroids)
(use-package perspective
  :init
  (setq persp-initial-frame-name "dev"))
(use-package wgrep)
(use-package avy)
(use-package fzf)
(use-package vundo)
(use-package savehist)
(use-package recentf)
(use-package windower)
(use-package ido-select-window)
(use-package magit)
(use-package magit-delta)
(use-package which-key)
(use-package yasnippet)
(use-package yasnippet-snippets)
(use-package ediff)
(use-package sudo-edit)
(use-package rainbow-mode)
(use-package all-the-icons)
(use-package all-the-icons-dired)
(use-package diredfl)
(use-package dired-subtree)
(use-package org-superstar)
(use-package toc-org)
(use-package gruvbox-theme)
(use-package eglot)
(use-package treesit-auto)
(use-package rust-mode)
(use-package cargo)
(use-package cargo-mode)
(use-package haskell-mode)
(use-package cmake-ts-mode)

(set-face-attribute 'default nil
                    :font "JetBrainsMono Nerd Font Mono"
                    :height 120
                    :weight 'semi-bold)
(fset 'yes-or-no-p 'y-or-n-p)
(treesit-auto-add-to-auto-mode-alist 'all)
(unless (member "all-the-icons" (font-family-list))
  (all-the-icons-install-fonts t))
(customize-set-variable 'persp-mode-prefix-key (kbd "C-c M-p"))

(global-treesit-auto-mode 1)
(global-company-mode 1)
(diredfl-global-mode 1)
(global-hl-line-mode 1)
(global-display-line-numbers-mode 1)
(global-font-lock-mode 1)
(global-visual-line-mode 1)
(yas-global-mode 1)

(global-auto-revert-mode 0)

(meow-global-mode 1)
(vertico-mode 1)
(vertico-flat-mode 1)
(marginalia-mode 1)
(savehist-mode 1)
(recentf-mode 1)
(electric-pair-mode 1)
(electric-indent-mode 1)
(file-name-shadow-mode 1)
(minibuffer-depth-indicate-mode 1)
(which-key-mode 1)
(winner-mode 1)
(persp-mode 1)
(delete-selection-mode 1)

(tab-bar-mode 0)
(menu-bar-mode 0)
(tool-bar-mode 0)
(blink-cursor-mode 0)
(desktop-save-mode 0)
(scroll-bar-mode 0)

(add-hook 'eglot-managed-mode-hook (lambda () (eglot-inlay-hints-mode -1)))
(add-hook 'embark-collect-mode-hook #'consult-preview-at-point-mode)
(add-hook 'org-mode-hook #'org-indent-mode)
(add-hook 'org-mode-hook #'org-superstar-mode)
(add-hook 'org-mode-hook #'toc-org-enable)
(add-hook 'rfn-eshadow-update-overlay-hook #'vertico-directory-tidy)
(add-hook 'text-mode-hook 'visual-line-mode)
(add-hook 'write-file-functions 'delete-trailing-whitespace)
(add-hook 'before-save-hook #'my--eglot-format-buffer-on-save)
(add-hook 'magit-mode-hook 'magit-auto-revert-mode)
(add-hook 'magit-blame-mode-hook #'my-toggle-meow-normal-mode)
(add-hook 'magit-mode-hook (lambda () (my--rename-buffer-to-star 'magit-mode "")))
(add-hook 'dired-mode-hook (lambda () (my--rename-buffer-to-star 'dired-mode "dired: ")))
(add-hook 'dired-mode-hook #'all-the-icons-dired-mode)
(add-hook 'ido-setup-hook (lambda ()
                            (keymap-set ido-completion-map "C-n" #'ido-next-match)
                            (keymap-set ido-completion-map "C-p" #'ido-prev-match)))
(add-hook 'kill-emacs-hook #'persp-state-save)

(add-to-list 'default-frame-alist '(font . "JetBrainsMono Nerd Font Mono-10"))
(add-to-list 'default-frame-alist '(undecorated . t))
(add-to-list 'auto-mode-alist '("CMakeLists\\.txt\\'" . cmake-ts-mode))
(add-to-list 'auto-mode-alist '("\\.cmake\\'" . cmake-ts-mode))
(add-to-list 'consult-buffer-sources persp-consult-source)

(load-file "~/.config/emacs/odin-ts-mode/odin-ts-mode.el")

(consult-customize consult--source-buffer :hidden t :default nil)

(defvar my--vertico-toggle-state t)

(setq-default indent-tabs-mode nil)
(setq-default tab-width 4)

(setq backup-directory-alist `(("." . ,(locate-user-emacs-file "backup"))))
(setq auto-save-file-name-transforms `((".*" ,(locate-user-emacs-file "backup/autosaves"))))
(setq
 delete-old-versions t
 kept-new-versions 6
 kept-old-versions 2
 version-control t)
(setq frame-title-format
      '(:eval (if (buffer-file-name)
                  (concat "" (abbreviate-file-name (buffer-file-name)))
                (concat "" "%b"))))
(setq display-buffer-alist
      '(("\\*Help\\*\\|\\*Messages\\*\\|\\*Warnings\\*\\|\\*Embark Export\\|\\*Embark Collect\\|\\*compilation\\*\\|\\*Flymake\\|\\*Async Shell Command\\*\\|\\*Occur\\*\\|\\*grep\\*\\|\\*xref\\*"
         (display-buffer-reuse-window
          display-buffer-in-side-window)
         (body-function . select-window))
        ("\\*Embark Actions\\*"
         (display-buffer-no-window)
         (allow-no-window . t))))
(setq meow-keypad-describe-keymap-function nil)
(setq meow-expand-hint-remove-delay 0)
(setq completion-styles '(orderless))
(setq completion-category-overrides '((file (styles . (partial-completion)))))
(setq consult-ripgrep-args (concat consult-ripgrep-args " -P"))
(setq consult-fd-args "fd --full-path --hidden --no-ignore --color=never --exclude .git")
(setq consult-buffer-filter "\\*")
(setq consult-preview-key "C-o")
(setq company-tooltip-maximum-width 10000)
(setq persp-state-default-file (locate-user-emacs-file "state.persp"))
(setq persp-sort 'access)
(setq wgrep-auto-save-buffer t)
(setq mc/always-run-for-all t)
(setq compile-command "")
(setq avy-background t)
(setq avy-keys '(?a ?r ?s ?t ?g ?m ?n ?e ?i ?o ?w ?f ?p ?l ?u ?y ?x ?c ?d ?h))
(setq vundo-glyph-alist vundo-unicode-symbols)
(setq recentf-exclude '("/tmp"))
(setq magit-delta-default-dark-theme "gruvbox-dark")
(setq ediff-split-window-function 'split-window-horizontally)
(setq ediff-window-setup-function 'ediff-setup-windows-plain)
(setq rainbow-x-colors nil)
(setq org-superstar-headline-bullets-list '("◉" "○" "◎"))
(setq org-src-fontify-natively t)
(setq org-indent-indentation-per-level 4)
(setq dired-listing-switches "-alh --group-directories-first")
(setq dired-kill-when-opening-new-dired-buffer t)
(setq dired-dwim-target t)
(setq dired-subtree-use-backgrounds nil)
(setq wdired-create-parent-directories t)
(setq wdired-allow-to-change-permissions t)
(setq icon-title-format frame-title-format)
(setq display-line-numbers-type 'relative)
(setq treesit-auto-install t)
(setq treesit-font-lock-level 4)
(setq c-ts-mode-indent-offset 4)
(setq go-ts-mode-indent-offset 4)
(setq tab-bar-show nil)
(setq tab-bar-new-button-show nil)
(setq tab-bar-close-button-show nil)
(setq use-short-answers t)
(setq scroll-error-top-bottom t)
(setq enable-recursive-minibuffers t)
(setq auto-revert-verbose nil)
(setq auto-revert-check-vc-info t)
(setq ibuffer-default-sorting-mode 'filename/process)
(setq window-min-width 1)
(setq window-min-height 1)
(setq split-height-threshold nil)
(setq split-width-threshold 200)
(setq visible-bell nil)
(setq ring-bell-function 'ignore)
(setq isearch-lazy-count t)
(setq search-whitespace-regexp ".*?")
(setq completion-ignore-case t)
(setq read-buffer-completion-ignore-case t)
(setq lazy-count-prefix-format "(%s/%s) ")
(setq lazy-count-suffix-format nil)
(setq inhibit-startup-screen t)
(setq initial-scratch-message nil)

(defadvice vr--isearch (around add-case-insensitive (forward string &optional bound noerror count) activate)
  (when (and (eq vr/engine 'python) case-fold-search)
    (setq string (concat "(?i)" string)))
  ad-do-it)

(defun my--eglot-format-buffer-on-save ()
  (when (eglot-managed-p)
    (eglot-format-buffer)))

(defun my--rename-buffer-to-star (mode str)
  (when (derived-mode-p mode)
    (let ((current-name (buffer-name)))
      (unless (string-prefix-p "*" current-name)
        (rename-buffer (concat "*" str current-name "*") t)))))

(defun my--half-window-height ()
  (max 1 (/ (window-body-height) 2)))

(defun my--isearch-with-region (forward)
  (if (use-region-p)
      (let ((search-string (buffer-substring-no-properties (region-beginning) (region-end))))
        (deactivate-mark)
        (isearch-mode forward)
        (isearch-yank-string search-string))
    (if forward
        (isearch-forward)
      (isearch-backward))))

(defun my--consult-fd-with-region ()
  (if (use-region-p)
      (consult-fd nil (buffer-substring-no-properties (region-beginning) (region-end)))
    (consult-fd)))

(defun my--consult-ripgrep-with-region ()
  (if (use-region-p)
      (consult-ripgrep nil (buffer-substring-no-properties (region-beginning) (region-end)))
    (consult-ripgrep)))

(defun my--consult-line-with-region ()
  (if (use-region-p)
      (let ((input (buffer-substring-no-properties (region-beginning) (region-end))))
        (consult-line input))
    (consult-line)))

(defun my--move-lines (n)
  (let* (text-start
         text-end
         (region-start (point))
         (region-end region-start)
         swap-point-mark
         delete-latest-newline)
    (when (region-active-p)
      (if (> (point) (mark))
          (setq region-start (mark))
        (exchange-point-and-mark)
        (setq swap-point-mark t
              region-end (point))))
    (end-of-line)
    (if (< (point) (point-max))
        (forward-char 1)
      (setq delete-latest-newline t)
      (insert-char ?\n))
    (setq text-end (point)
          region-end (- region-end text-end))
    (goto-char region-start)
    (beginning-of-line)
    (setq text-start (point)
          region-start (- region-start text-end))
    (let ((text (delete-and-extract-region text-start text-end)))
      (forward-line n)
      (when (not (= (current-column) 0))
        (insert-char ?\n)
        (setq delete-latest-newline t))
      (insert text))
    (forward-char region-end)
    (when delete-latest-newline
      (save-excursion
        (goto-char (point-max))
        (delete-char -1)))
    (when (region-active-p)
      (setq deactivate-mark nil)
      (set-mark (+ (point) (- region-start region-end)))
      (if swap-point-mark
          (exchange-point-and-mark)))))

(defun my--call-with-vertico (fn &rest arg)
  (let ((vertico-flat-on (bound-and-true-p vertico-flat-mode)))
    (unwind-protect
        (progn
          (when vertico-flat-on
            (vertico-flat-mode -1))
          (apply fn arg))
      (when vertico-flat-on
        (vertico-flat-mode 1)))))

(defun my-scroll-up-half ()
  (interactive)
  (previous-line (my--half-window-height))
  (recenter))

(defun my-scroll-down-half ()
  (interactive)
  (next-line (my--half-window-height))
  (recenter))

(defun my-copy-full-path ()
  (interactive)
  (let ((file-path (or (buffer-file-name) default-directory)))
    (kill-new file-path)
    (message "Copied '%s'" file-path)))

(defun my-copy-path ()
  (interactive)
  (let ((dir-path (or (and (buffer-file-name)
                           (file-name-directory (buffer-file-name)))
                      default-directory)))
    (kill-new (directory-file-name dir-path))
    (message "Copied '%s'" dir-path)))

(defun my-copy-file-name ()
  (interactive)
  (if-let ((file-name (buffer-file-name)))
      (progn
        (kill-new (file-name-nondirectory file-name))
        (message "Copied '%s'" (file-name-nondirectory file-name)))
    (message "Buffer is not visiting a file!")))

(defun my-kill-all-side-windows ()
  (interactive)
  (let ((windows (window-list)))
    (dolist (window windows)
      (when (window-parameter window 'window-side)
        (delete-window window)))))

(defun my-delete-other-windows ()
 (interactive)
 (let ((buffer-name (buffer-name)))
   (while (window-parameter (selected-window) 'window-side)
     (other-window 1))
   (delete-other-windows)
   (switch-to-buffer buffer-name)))

(defun my-persp-kill-other-buffers ()
  (interactive)
  (cl-loop for buf in (persp-current-buffers)
           unless (or (eq buf (current-buffer))
                      (eq buf (get-buffer (persp-scratch-buffer))))
           do (kill-buffer buf))
  (message nil))

(defun my-kill-region-or-line ()
  (interactive)
  (if (use-region-p)
      (kill-region (region-beginning) (region-end))
    (kill-line)))

(defun my-delete-line-above ()
  (interactive)
  (save-excursion
    (forward-line -1)
    (kill-whole-line)))

(defun my-toggle-meow-normal-mode ()
  (interactive)
  (if (meow-motion-mode-p)
      (meow-normal-mode)
    (meow-motion-mode)))

(defun my-toggle-vertico-flat-mode ()
  (interactive)
  (if my--vertico-toggle-state
      (progn
        (vertico-flat-mode 0)
        (setq my--vertico-toggle-state nil)
        (message "vertico flat mode off"))
    (progn
      (vertico-flat-mode 1)
      (setq my--vertico-toggle-state t)
      (message "vertico flat mode on"))))

(defun my-toggle-magit-blame ()
  (interactive)
  (if (bound-and-true-p magit-blame-mode)
      (magit-blame-quit)
    (call-interactively 'magit-blame-addition)))

(defun my-isearch-forward-with-region ()
  (interactive)
  (my--isearch-with-region t))

(defun my-isearch-backward-with-region ()
  (interactive)
  (my--isearch-with-region nil))

(defun my-fzf-file ()
  (interactive)
    (if (project-current)
        (fzf-git-files)
      (fzf-find-file))
    (meow-insert-mode))

(defun my-move-lines-up (&optional n)
  (interactive "p")
  (my--move-lines (- (or n 1))))

(defun my-move-lines-down (&optional n)
  (interactive "p")
  (my--move-lines (or n 1)))

(defun my-tmux-to-emacs-buffer ()
  (interactive)
  (let ((output (shell-command-to-string "tmux capture-pane -pS -1000")))
    (with-current-buffer (get-buffer-create "*tmux-export*")
      (erase-buffer)
      (insert output)
      (meow-motion-mode)
      (meow-normal-mode)
      (goto-char (point-max))
      (skip-chars-backward " \t\n")
      (switch-to-buffer-other-window "*tmux-export*"))))

(defun add-keymap (map func key desc)
  (keymap-set map key func)
  (which-key-add-keymap-based-replacements map key desc))

(defvar-keymap my-normal-map)
(add-keymap global-map my-normal-map "C-x a" "normal map")
(meow-define-keys
    'normal
  (cons "SPC" my-normal-map))
(meow-define-keys
    'motion
  (cons "SPC" my-normal-map))

(meow-normal-define-key '("<escape>" . (lambda () (interactive) (ignore) (keyboard-quit))))
(meow-normal-define-key '("j" . move-beginning-of-line))
(meow-normal-define-key '("f" . back-to-indentation))
(meow-normal-define-key '("o" . move-end-of-line))
(meow-normal-define-key '("u" . clipboard-yank))
(meow-normal-define-key '(";" . mark-defun))
(meow-normal-define-key '("J" . backward-up-list))
(meow-normal-define-key '("F" . backward-list))
(meow-normal-define-key '("O" . forward-list))
(meow-normal-define-key '("U" . (lambda () (interactive) (my--call-with-vertico 'consult-yank-pop))))
(meow-normal-define-key '("y" . repeat))
(meow-normal-define-key '("h" . backward-char))
(meow-normal-define-key '("a" . next-line))
(meow-normal-define-key '("e" . previous-line))
(meow-normal-define-key '("i" . forward-char))
(meow-normal-define-key '("H" . join-line))
(meow-normal-define-key '("A" . (lambda () (interactive) (meow-open-below) (meow-normal-mode))))
(meow-normal-define-key '("E" . (lambda () (interactive) (meow-open-above) (meow-normal-mode))))
(meow-normal-define-key '("I" . (lambda () (interactive) (join-line -1))))
(meow-normal-define-key '("k" . kill-whole-line))
(meow-normal-define-key '("p" . mark-word))
(meow-normal-define-key '("," . er/expand-region))
(meow-normal-define-key '("." . er/contract-region))
(meow-normal-define-key '("/" . mark-paragraph))
(meow-normal-define-key '("K" . my-delete-line-above))
(meow-normal-define-key '("P" . mark-sexp))
(meow-normal-define-key '("l" . clipboard-kill-ring-save))
(meow-normal-define-key '("d" . backward-word))
(meow-normal-define-key '("c" . forward-word))
(meow-normal-define-key '("b" . undo))
(meow-normal-define-key '("D" . (lambda () (interactive) (forward-symbol -1))))
(meow-normal-define-key '("C" . (lambda () (interactive) (forward-symbol 1))))
(meow-normal-define-key '("B" . undo-redo))
(meow-normal-define-key '("n" . set-mark-command))
(meow-normal-define-key '("r" . exchange-point-and-mark))
(meow-normal-define-key '("t" . meow-insert))
(meow-normal-define-key '("s" . meow-append))
(meow-normal-define-key '("g" . avy-goto-line))
(meow-normal-define-key '("n" . set-mark-command))
(meow-normal-define-key '("G" . goto-line))
(meow-normal-define-key '("x" . meow-replace))
(meow-normal-define-key '("m" . meow-change))
(meow-normal-define-key '("w" . my-kill-region-or-line))
(meow-normal-define-key '("v" . meow-line))
(meow-normal-define-key '("?" . set-mark-command))
(meow-normal-define-key '("-" . my-scroll-up-half))
(meow-normal-define-key '("+" . my-scroll-down-half))
(meow-normal-define-key '("(" . backward-paragraph))
(meow-normal-define-key '(")" . forward-paragraph))
(meow-normal-define-key '("{" . (lambda () (interactive) (beginning-of-defun) (recenter))))
(meow-normal-define-key '("}" . (lambda () (interactive) (end-of-defun) (recenter))))
(meow-normal-define-key '("<" . beginning-of-buffer))
(meow-normal-define-key '(">" . end-of-buffer))

(meow-motion-overwrite-define-key '("<escape>" . (lambda () (interactive) (ignore) (keyboard-quit))))
(meow-motion-overwrite-define-key '("," . er/expand-region))
(meow-motion-overwrite-define-key '("." . er/contract-region))
(meow-motion-overwrite-define-key '("(" . backward-paragraph))
(meow-motion-overwrite-define-key '(")" . forward-paragraph))
(meow-motion-overwrite-define-key '("a" . next-line))
(meow-motion-overwrite-define-key '("e" . previous-line))

(defvar-keymap my-find-keymap)
(add-keymap my-find-keymap #'(lambda () (interactive) (my--call-with-vertico 'my--consult-fd-with-region)) "h" "consult-fd")
(add-keymap my-find-keymap #'(lambda () (interactive) (my--call-with-vertico 'consult-fd 1)) "a" "consult-fd-1")
(add-keymap my-find-keymap #'(lambda () (interactive) (my--call-with-vertico 'fzf-find-file-in-dir) (meow-insert-mode)) "o" "fzf-find-file-in-dir")
(add-keymap my-find-keymap #'my-fzf-file "f" "my-fzf-file")
(add-keymap my-normal-map my-find-keymap "s" "my-find-keymap")

(defvar-keymap my-search-keymap)
(add-keymap my-search-keymap #'(lambda () (interactive) (my--call-with-vertico 'my--consult-ripgrep-with-region)) "h" "consult-ripgrep")
(add-keymap my-search-keymap #'(lambda () (interactive) (my--call-with-vertico 'consult-ripgrep 1)) "a" "consult-ripgrep-1")
(add-keymap my-search-keymap #'(lambda () (interactive) (my--call-with-vertico 'my--consult-line-with-region)) "f" "consult-line")
(add-keymap my-search-keymap #'(lambda () (interactive) (my--call-with-vertico 'consult-imenu)) "o" "consult-imenu")
(add-keymap my-normal-map my-search-keymap "t" "my-search-keymap")

(defvar-keymap my-replace-keymap)
(add-keymap my-replace-keymap #'query-replace "h" "query-replace")
(add-keymap my-replace-keymap #'vr/replace "a" "vr/replace")
(add-keymap my-replace-keymap #'vr/mc-mark "e" "vr/mc-mark")
(add-keymap my-normal-map my-replace-keymap "r" "my-replace-keymap")

(defvar-keymap my-magit-keymap)
(add-keymap my-magit-keymap #'magit-status "h" "magit-status")
(add-keymap my-magit-keymap #'magit-file-dispatch "a" "magit-file-dispatch")
(add-keymap my-magit-keymap #'magit-checkout "e" "magit-checkout")
(add-keymap my-magit-keymap #'magit-log-current "f" "magit-log-current")
(add-keymap my-magit-keymap #'my-toggle-magit-blame "o" "magit-blame")
(add-keymap my-normal-map my-magit-keymap "n" "my/combo-magit-map")

(add-keymap my-normal-map #'persp-switch "l" "persp-switch")
(add-keymap my-normal-map #'ido-select-window "d" "ido-select-window")
(add-keymap my-normal-map #'consult-buffer "c" "consult-buffer")
(add-keymap my-normal-map #'consult-bookmark "b" "consult-bookmark")
(add-keymap my-normal-map #'find-file "w" "find-file")

(defvar-keymap my-compile-keymap)
(add-keymap my-compile-keymap #'project-compile "f" "project-compile")
(add-keymap my-compile-keymap #'project-async-shell-command "o" "project-async-shell-command")
(add-keymap my-compile-keymap #'compile "h" "compile")
(add-keymap my-compile-keymap #'async-shell-command "a" "async-shell-command")
(add-keymap my-compile-keymap #'recompile "e" "recompile")
(add-keymap my-normal-map my-compile-keymap "m" "compile")

(defvar-keymap my-xref-keymap)
(add-keymap my-xref-keymap #'xref-go-back "f" "xref-go-back")
(add-keymap my-xref-keymap #'xref-go-forward "o" "xref-go-forward")
(add-keymap my-xref-keymap #'xref-find-definitions "h" "xref-find-definitions")
(add-keymap my-xref-keymap #'xref-find-references "a" "xref-find-references")
(add-keymap my-normal-map my-xref-keymap "x" "my-xref-keymap")

(defvar-keymap my-window-keymap)
(add-keymap my-window-keymap #'kill-buffer-and-window "l" "kill-buffer-and-window")
(add-keymap my-window-keymap #'my-delete-other-windows "d" "my-delete-other-windows")
(add-keymap my-window-keymap #'delete-window "c" "delete-window")
(add-keymap my-window-keymap #'(lambda () (interactive) (delete-other-windows-vertically) (my-kill-all-side-windows)) "b" "delete-side-and-vertical")
(add-keymap my-window-keymap #'balance-windows "n" "balance-windows")
(add-keymap my-window-keymap #'windower-toggle-split "r" "windower-toggle-split")
(add-keymap my-window-keymap #'split-window-vertically "t" "split-window-vertically")
(add-keymap my-window-keymap #'split-window-horizontally "s" "split-window-horizontally")
(add-keymap my-window-keymap #'windower-toggle-single "w" "windower-toggle-single")
(add-keymap my-window-keymap #'(lambda () (interactive) (windower-swap-left) (select-window (old-selected-window))) "h" "windower-swap-left")
(add-keymap my-window-keymap #'(lambda () (interactive) (windower-swap-below) (select-window (old-selected-window))) "a" "windower-swap-below")
(add-keymap my-window-keymap #'(lambda () (interactive) (windower-swap-above) (select-window (old-selected-window))) "e" "windower-swap-above")
(add-keymap my-window-keymap #'(lambda () (interactive) (windower-swap-right) (select-window (old-selected-window))) "i" "windower-swap-right")
(add-keymap my-normal-map my-window-keymap "h" "window-map")

(defvar-keymap my-file-keymap)
(add-keymap my-file-keymap #'my-copy-full-path"r" "copy full path")
(add-keymap my-file-keymap #'my-copy-path "t" "copy path")
(add-keymap my-file-keymap #'my-copy-file-name "s" "copy buffer name")
(defvar-keymap my-buffer-keymap)
(add-keymap my-buffer-keymap #'my-persp-kill-other-buffers "l" "my-persp-kill-other-buffers")
(add-keymap my-buffer-keymap #'persp-kill-buffer* "d" "persp-kill-buffer")
(add-keymap my-buffer-keymap #'kill-current-buffer "c" "kill-current-buffer")
(add-keymap my-buffer-keymap #'pop-to-mark-command "b" "pop-to-mark-command")
(add-keymap my-buffer-keymap my-file-keymap "n" "my-file-keymap")
(add-keymap my-buffer-keymap #'rename-buffer "r" "rename-buffer")
(add-keymap my-buffer-keymap #'previous-buffer "t" "prev-buffer")
(add-keymap my-buffer-keymap #'next-buffer "s" "next-buffer")
(add-keymap my-buffer-keymap #'revert-buffer "g" "revert-buffer")
(add-keymap my-buffer-keymap #'write-file "w" "write-file")
(add-keymap my-buffer-keymap #'(lambda () (interactive) (my--call-with-vertico 'consult-mark)) "m" "consult-mark")
(add-keymap my-buffer-keymap #'ediff-buffers "x" "ediff-buffers")
(add-keymap my-buffer-keymap #'align-regexp "z" "align-regexp")
(add-keymap my-buffer-keymap #'persp-ibuffer "a" "persp-ibuffer")
(add-keymap my-buffer-keymap #'(lambda () (interactive) (my--call-with-vertico 'consult-global-mark)) "M" "consult-global-mark")
(add-keymap my-normal-map my-buffer-keymap "a" "buffer-map")

(defvar-keymap my-persp-keymap)
(add-keymap my-persp-keymap #'persp-switch-to-scratch-buffer "l" "persp-switch-to-scratch-buffer")
(add-keymap my-persp-keymap #'persp-kill-others "d" "persp-kill-others")
(add-keymap my-persp-keymap #'persp-kill "c" "persp-kill")
(add-keymap my-persp-keymap #'persp-rename "r" "persp-rename")
(add-keymap my-persp-keymap #'persp-prev "t" "persp-prev")
(add-keymap my-persp-keymap #'persp-next "s" "persp-next")
(add-keymap my-persp-keymap #'persp-merge "w" "persp-merge")
(add-keymap my-persp-keymap #'persp-unmerge "m" "persp-unmerge")
(add-keymap my-normal-map my-persp-keymap "e" "my-persp-keymap")

(defvar-keymap my-bookmark-keymap)
(add-keymap my-bookmark-keymap #'bookmark-delete "c" "bookmark-delete")
(add-keymap my-bookmark-keymap #'bookmark-rename "r" "bookmark-rename")
(add-keymap my-bookmark-keymap #'bookmark-set "s" "bookmark-set")
(add-keymap my-normal-map my-bookmark-keymap "i" "my-bookmark-keymap")

(defvar-keymap my-eglot-keymap)
(add-keymap my-eglot-keymap #'eglot "e" "eglot")
(add-keymap my-eglot-keymap #'eglot-shutdown "c" "eglot-shutdown")
(add-keymap my-eglot-keymap #'eglot-format "f" "eglot-format")
(add-keymap my-eglot-keymap #'flymake-show-buffer-diagnostics "b" "buffer-diagnostics")
(add-keymap my-eglot-keymap #'flymake-show-project-diagnostics "p" "project-diagnostics")
(add-keymap global-map my-eglot-keymap "C-c e" "my-eglot-keymap")

(keymap-set global-map "C-h" #'mark-word)
(keymap-set global-map "C-c u" #'vundo)
(keymap-set global-map "C-c h" #'help-command)
(keymap-set global-map "C-c i" #'indent-region)
(keymap-set global-map "C-c v" #'my-toggle-vertico-flat-mode)
(keymap-set global-map "C-c n" #'my-toggle-meow-normal-mode)
(keymap-set global-map "M-<delete>" #'kill-word)
(keymap-set global-map "C-=" #'global-text-scale-adjust)
(keymap-set global-map "C-s" #'my-isearch-forward-with-region)
(keymap-set global-map "C-r" #'my-isearch-backward-with-region)
(keymap-set global-map "C-S-s" #'vr/isearch-forward)
(keymap-set global-map "C-S-r" #'vr/isearch-backward)
(keymap-set global-map "M-/" #'xref-find-references)
(keymap-set global-map "M-a" #'my-move-lines-down)
(keymap-set global-map "M-e" #'my-move-lines-up)
(keymap-set global-map "M-o" #'mc/mark-previous-like-this)
(keymap-set global-map "M-u" #'mc/mark-next-like-this)
(keymap-set global-map "C-," #'duplicate-dwim)
(keymap-set global-map "C-." #'embark-act)
(keymap-set global-map "C-;" #'comment-line)

(keymap-set occur-mode-map "M-a" #'occur-edit-mode)
(keymap-set grep-mode-map "M-a" #'wgrep-change-to-wgrep-mode)
(keymap-set dired-mode-map "M-a" #'dired-toggle-read-only)
(keymap-set minibuffer-local-map "M-a" #'embark-export)
(keymap-set occur-mode-map "o" (lambda () (interactive) (occur-mode-goto-occurrence) (select-window (old-selected-window))))
(keymap-set compilation-button-map "o" (lambda () (interactive) (compile-goto-error) (select-window (old-selected-window))))
(keymap-set transient-map "<escape>" #'transient-quit-one)
(keymap-set mc/keymap "<return>" nil)

(keymap-set magit-blame-mode-map "n" (lambda () (interactive) (magit-blame-next-chunk) (recenter)))
(keymap-set magit-blame-mode-map "p" (lambda () (interactive) (magit-blame-previous-chunk) (recenter)))
(keymap-set magit-blame-read-only-mode-map "n" (lambda () (interactive) (magit-blame-next-chunk) (recenter)))
(keymap-set magit-blame-read-only-mode-map "p" (lambda () (interactive) (magit-blame-previous-chunk) (recenter)))
(keymap-set magit-stash-mode-map "n" (lambda () (interactive) (magit-section-forward) (recenter)))
(keymap-set magit-stash-mode-map "p" (lambda () (interactive) (magit-section-backward) (recenter)))
(keymap-set magit-revision-mode-map "n" (lambda () (interactive) (magit-section-forward) (recenter)))
(keymap-set magit-revision-mode-map "p" (lambda () (interactive) (magit-section-backward) (recenter)))
(keymap-set magit-status-mode-map "n" (lambda () (interactive) (magit-section-forward) (recenter)))
(keymap-set magit-status-mode-map "p" (lambda () (interactive) (magit-section-backward) (recenter)))
(keymap-set magit-mode-map "C-<tab>" #'magit-section-cycle-diffs)

(keymap-set dired-mode-map "h" #'dired-up-directory)
(keymap-set dired-mode-map "i" #'dired-find-alternate-file)
(keymap-set dired-mode-map "n" #'dired-display-file)
(keymap-set dired-mode-map "<return>" #'dired-find-file-other-window)
(keymap-set dired-mode-map "<tab>" #'dired-subtree-toggle)
(keymap-set dired-mode-map "TAB" #'dired-subtree-toggle)
(keymap-set dired-mode-map "<backtab>" #'dired-subtree-remove)
(keymap-set dired-mode-map "S-TAB" #'dired-subtree-remove)

(load-file (locate-user-emacs-file "color-theme.el"))
(server-start)
