[colors.bright]
black = "#3c3836"
blue = "#7daea3"
cyan = "#89b482"
green = "#a9b665"
magenta = "#d3869b"
red = "#ea6962"
white = "#d4be98"
yellow = "#d8a657"

[colors.normal]
black = "#3c3836"
blue = "#7daea3"
cyan = "#89b482"
green = "#a9b665"
magenta = "#d3869b"
red = "#ea6962"
white = "#d4be98"
yellow = "#d8a657"

[colors.primary]
background = "#282828"
foreground = "#d4be98"

[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.normal]
family = "JetBrains Mono"
style = "SemiBold"

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[scrolling]
history = 50000

[window]
opacity = 1.0
decorations = "none"
