;;; -*- lexical-binding: t; coding: utf-8 -*-

(setq kind-icon-mapping
      '((array          "a"   :icon "symbol-array"       :face font-lock-constant-face :collection "vscode")
        (boolean        "b"   :icon "symbol-boolean"     :face font-lock-constant-face :collection "vscode")
        (color          "#"   :icon "symbol-color"       :face font-lock-constant-face :collection "vscode")
        (command        "cm"  :icon "chevron-right"      :face font-lock-constant-face :collection "vscode")
        (constant       "co"  :icon "symbol-constant"    :face font-lock-constant-face :collection "vscode")
        (class          "c"   :icon "symbol-class"       :face font-lock-constant-face :collection "vscode")
        (constructor    "cn"  :icon "symbol-method"      :face font-lock-constant-face :collection "vscode")
        (enum           "e"   :icon "symbol-enum"        :face font-lock-constant-face :collection "vscode")
        (enummember     "em"  :icon "symbol-enum-member" :face font-lock-constant-face :collection "vscode")
        (enum-member    "em"  :icon "symbol-enum-member" :face font-lock-constant-face :collection "vscode")
        (event          "ev"  :icon "symbol-event"       :face font-lock-constant-face :collection "vscode")
        (field          "fd"  :icon "symbol-field"       :face font-lock-constant-face :collection "vscode")
        (file           "f"   :icon "symbol-file"        :face font-lock-constant-face :collection "vscode")
        (folder         "d"   :icon "folder"             :face font-lock-constant-face :collection "vscode")
        (function       "f"   :icon "symbol-method"      :face font-lock-constant-face :collection "vscode")
        (interface      "if"  :icon "symbol-interface"   :face font-lock-constant-face :collection "vscode")
        (keyword        "kw"  :icon "symbol-keyword"     :face font-lock-constant-face :collection "vscode")
        (macro          "mc"  :icon "lambda"             :face font-lock-constant-face)
        (magic          "ma"  :icon "lightbulb-autofix"  :face font-lock-constant-face :collection "vscode")
        (method         "m"   :icon "symbol-method"      :face font-lock-constant-face :collection "vscode")
        (module         "{"   :icon "file-code-outline"  :face font-lock-constant-face)
        (numeric        "nu"  :icon "symbol-numeric"     :face font-lock-constant-face :collection "vscode")
        (operator       "op"  :icon "symbol-operator"    :face font-lock-constant-face :collection "vscode")
        (param          "pa"  :icon "gear"               :face font-lock-constant-face :collection "vscode")
        (property       "pr"  :icon "symbol-property"    :face font-lock-constant-face :collection "vscode")
        (reference      "rf"  :icon "library"            :face font-lock-constant-face :collection "vscode")
        (snippet        "S"   :icon "symbol-snippet"     :face font-lock-constant-face :collection "vscode")
        (string         "s"   :icon "symbol-string"      :face font-lock-constant-face :collection "vscode")
        (struct         "%"   :icon "symbol-structure"   :face font-lock-constant-face :collection "vscode")
        (text           "tx"  :icon "symbol-key"         :face font-lock-constant-face :collection "vscode")
        (typeparameter  "tp"  :icon "symbol-parameter"   :face font-lock-constant-face :collection "vscode")
        (type-parameter "tp"  :icon "symbol-parameter"   :face font-lock-constant-face :collection "vscode")
        (unit           "u"   :icon "symbol-ruler"       :face font-lock-constant-face :collection "vscode")
        (value          "v"   :icon "symbol-enum"        :face font-lock-constant-face :collection "vscode")
        (variable       "va"  :icon "symbol-variable"    :face font-lock-constant-face :collection "vscode")
        (t              "."   :icon "question"           :face font-lock-constant-face :collection "vscode")))

(provide 'my-kind-icon-mapping)
